/*How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?*/

//Ans: 9183

import java.util.*;
import java.math.BigInteger;

class Prob029
{
	public static void main(String args[])
	{
		long start=System.currentTimeMillis();

		int n=99;			//Upper limit - lower limit +1

		int k=0, j, i;

		BigInteger B[][]=new BigInteger[n][n];
		BigInteger sort[]= new BigInteger[n*n];

		int len=sort.length;

		int a=2, b=2;

		for (a=2; a<=n+1; a++)
			for (b=2; b<=n+1; b++)
			{
				sort[k]=(new BigInteger(a+"")).pow(b);
				k++;
			}

		for (j=0; j<len-1; j++)
		{
			for (i=0; i<len-1; i++)
			{
				if (sort[i].compareTo(sort[i+1])>0)
				{
					BigInteger temp=sort[i];
					sort[i]=sort[i+1];
					sort[i+1]=temp;
				}
			}
		}
		for (i=0; i<len-1; i++)
			for (j=0; j<len-1; j++)
				if (sort[j].compareTo(sort[j+1])==0)
				{
					for (k=j; k<len-1; k++)
						sort[k]=sort[k+1];

					len--;
				}

//		for (i=0; i<len; i++)
//			System.out.print(" "+sort[i]);

		long end=System.currentTimeMillis();

		System.out.println("\nThe no. of elements are: "+len);
		System.out.println("Exec time: "+(end-start));
	}
}